Repository ES2-UFPI/CajehForm, pull requests merged in 2019-10, with the labels that each got.

#27 cajeh#18
  frontEnd/src/LobbyScreen/Lobby.js
  frontEnd/src/LobbyScreen/LobbyScreen.js
  frontEnd/src/MaterialScreen/MaterialScreen.js
  frontEnd/src/PublishScreen/Publish.js
  frontEnd/src/PublishScreen/PublishScreen.js
Labels: View

#30 John#21
  frontEnd/src/Components/Publish.js
Labels: Componente

#31 Lucas#26
  backEnd/.tool-versions
  backEnd/cajehform/.gitignore
  backEnd/cajehform/.rspec
  backEnd/cajehform/.ruby-version
  backEnd/cajehform/Gemfile
  backEnd/cajehform/Gemfile.lock
  backEnd/cajehform/Rakefile
  backEnd/cajehform/app/channels/application_cable/channel.rb
  backEnd/cajehform/app/channels/application_cable/connection.rb
  backEnd/cajehform/app/controllers/application_controller.rb
  backEnd/cajehform/app/controllers/concerns/.keep
  backEnd/cajehform/app/jobs/application_job.rb
  backEnd/cajehform/app/mailers/application_mailer.rb
  backEnd/cajehform/app/models/application_record.rb
  backEnd/cajehform/app/models/concerns/.keep
  backEnd/cajehform/app/views/layouts/mailer.html.erb
  backEnd/cajehform/app/views/layouts/mailer.text.erb
  backEnd/cajehform/bin/bundle
  backEnd/cajehform/bin/rails
  backEnd/cajehform/bin/rake
  backEnd/cajehform/bin/setup
  backEnd/cajehform/bin/spring
  backEnd/cajehform/config.ru
  backEnd/cajehform/config/application.rb
  backEnd/cajehform/config/boot.rb
  backEnd/cajehform/config/cable.yml
  backEnd/cajehform/config/credentials.yml.enc
  backEnd/cajehform/config/database.yml
  backEnd/cajehform/config/environment.rb
  backEnd/cajehform/config/environments/development.rb
  backEnd/cajehform/config/environments/production.rb
  backEnd/cajehform/config/environments/test.rb
  backEnd/cajehform/config/initializers/application_controller_renderer.rb
  backEnd/cajehform/config/initializers/backtrace_silencers.rb
  backEnd/cajehform/config/initializers/cors.rb
  backEnd/cajehform/config/initializers/filter_parameter_logging.rb
  backEnd/cajehform/config/initializers/inflections.rb
  backEnd/cajehform/config/initializers/mime_types.rb
  backEnd/cajehform/config/initializers/wrap_parameters.rb
  backEnd/cajehform/config/locales/en.yml
  backEnd/cajehform/config/puma.rb
  backEnd/cajehform/config/routes.rb
  backEnd/cajehform/config/spring.rb
  backEnd/cajehform/config/storage.yml
  backEnd/cajehform/db/seeds.rb
  backEnd/cajehform/lib/tasks/.keep
  backEnd/cajehform/log/.keep
  backEnd/cajehform/public/robots.txt
  backEnd/cajehform/spec/rails_helper.rb
  backEnd/cajehform/spec/spec_helper.rb
  backEnd/cajehform/storage/.keep
  backEnd/cajehform/tmp/.keep
  backEnd/cajehform/vendor/.keep
Labels: Ambiente

#34 Criar model de User
  backEnd/cajehform/app/controllers/users_controller.rb
  backEnd/cajehform/app/models/user.rb
  backEnd/cajehform/config/routes.rb
  backEnd/cajehform/db/migrate/20191009180525_create_users.rb
  backEnd/cajehform/spec/controllers/users_controller_spec.rb
  backEnd/cajehform/spec/models/user_spec.rb
  backEnd/cajehform/spec/requests/users_spec.rb
  backEnd/cajehform/spec/routing/users_routing_spec.rb
Labels: Classe

#37 Setup expo enviroment commands file
  frontEnd/expo.js
Labels: Ambiente

#64 cajeh#50
  cajeh-frontend/App.js
  cajeh-frontend/src/CollaboratorGear/BuildMaterial.js
  cajeh-frontend/src/CollaboratorGear/DoPublish.js
  cajeh-frontend/src/CollaboratorGear/EditMaterial.js
  cajeh-frontend/src/CollaboratorGear/MyMaterial.js
  cajeh-frontend/src/CollaboratorGear/MyPublish.js
  cajeh-frontend/src/Components/Builders/Builder.js
  cajeh-frontend/src/Components/Builders/ContentBuilder.js
  cajeh-frontend/src/Components/Builders/MaterialBuilder.js
  cajeh-frontend/src/Components/Lookers/CajehButton.js
  cajeh-frontend/src/Components/Lookers/Material.js
  cajeh-frontend/src/Components/Lookers/Page.js
  cajeh-frontend/src/Components/Lookers/Publish.js
  cajeh-frontend/src/SubscriberGear/LobbyScreen.js
  cajeh-frontend/src/SubscriberGear/MySaves.js
Labels: Ambiente
